# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81b4b31f371fbebf7d15790444967c9917b7dd905ad9b6f1a7381ec6a45881adf9edf62bc33f65af86db70a90ecfbe9e86599ffd5f9507939585eae600051b7e

test:
  secret_key_base: 8a99f9cd9b6c5cbb64de82ac06bf0f658c04db7f500d87ef01419995e63d70ff42a1e31e8e7259c56ea94ea3b15ddbe451a3b3b7d3b5cf4d6c910912bf374bab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
